Traceback (most recent call last):
  File "C:\Users\zschende\AppData\Local\miniforge3\envs\cimr-atbd\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\zschende\AppData\Local\miniforge3\envs\cimr-atbd\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zschende\AppData\Local\miniforge3\envs\cimr-atbd\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zschende\AppData\Local\miniforge3\envs\cimr-atbd\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\zschende\AppData\Local\miniforge3\envs\cimr-atbd\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\zschende\AppData\Local\miniforge3\envs\cimr-atbd\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\zschende\AppData\Local\miniforge3\envs\cimr-atbd\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os 
import sys
import numpy as np
import xarray as xr
import pyresample as pr
import importlib
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib import colors
from cartopy import crs as ccrs
import cmcrameri.cm as cmc

# local imports
if '/tools/' not in sys.path:
    sys.path.insert(0, os.path.abspath('../.../') + 'algorithm/tools/')
import l2_format as l2
import TSA_algorithm as algorithm
import l2_tools as tools
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 11[0m
[0;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m colors
[0;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcartopy[39;00m [38;5;28;01mimport[39;00m crs [38;5;28;01mas[39;00m ccrs
[1;32m---> 11[0m [38;5;28;01mimport[39;00m [38;5;21;01mcmcrameri[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcm[39;00m [38;5;28;01mas[39;00m [38;5;21;01mcmc[39;00m
[0;32m     13[0m [38;5;66;03m# local imports[39;00m
[0;32m     14[0m [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124m/tools/[39m[38;5;124m'[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m sys[38;5;241m.[39mpath:

[1;31mModuleNotFoundError[0m: No module named 'cmcrameri'

